// Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');

// Create an array of questions for user input
const questions = [
    {
    name: 'title',
    message: 'What is the title of your project?'
    },
    {
    name: 'names',
    message: 'What are the names of the contributors?'
    },
    {
    type: 'list',
    name: 'industry',
    message: 'What industry is this project most applicable to?',
    choices: 
        [
            'Information Technology',
            'Healthcare',
            'Finance',
            'Education',
            'Retail',
            'Manufacturing',
            'Hospitality',
            'Telecommunications',
            'Automotive',
            'Agriculture',
            'Media',
            'Energy',
            'Other'
        ],
    },
    {
    name: 'desc',
    message: 'Please provide a description of your project.'
    },
        {
    name: 'instalIns',
    message: 'Please provide install instructions for your users.'
    },
    {
    name: 'usageInfo',
    message: 'Please provide usage information for your users.'
    },
    {
    name: 'guidelines',
    message: 'Please provide contribution guidlines for your users.'
    },
    {
    name: 'testIns',
    message: 'Please provide test instructions for your users.'
    },
    {
    type: 'list',
    name: 'license',
    message: 'Please select which license the application is covered under.',
    choices: 
        [
            'Other'
        ]
    },
    {
    name: 'github',
    message: 'Please enter your GitHub username.'
    },
    {
    name: 'email',
    message: 'Please enter your email address.'
    },
]

// Create a function to write README file
function writeToFile(fileName, data) {

    fs.writeFile(fileName, data, (err) =>

    err ? console.error(err) : console.log('README.md generated') 

);
}
function generateReadme(answers) {

    return `# ${answers.title}\n\n${answers.names} contributed to this project.\n\nIndustry of this Application: ${answers.industry}\n\n${answers.desc}\n\n${answers.instalIns}\n\n${answers.usageInfo}\n\n${answers.guidlines}\n\n${answers.testIns}\n\n${answers.license}\n\nQuestions? Learn more at github.com/${answers.github}\n\n${answers.email}\n\nThis README file was generated by Zach Short.`;

}

// Create a function to initialize app
function startReadMeGenerator() {
    inquirer.prompt(questions)
    .then((answers) => {

      const readmeContent = generateReadme(answers); //generates the readME content using the answers object

      writeToFile('generatedREADME.md', readmeContent); // defines file name and writes all the info in
    })
    .catch((error) => console.error(error)); //triggers if theres an error
}

startReadMeGenerator();
